= java-mavenmixin-isisswagger
:_imagesdir: ./
:toc:

*As of 1.15.0, this module has been moved into Isis core*

This module, for use within link:http://isis.apache.org[Apache Isis] applications, provides a link:https://github.com/odavid/maven-plugins[maven mixin] that can be used to run the `swagger` goal of the link:http://isis.apache.org/guides/rgmvn.html[Apache Isis maven plugin] for a domain object model (to generate link:http://swagger.io/[swagger] definition files).
This reduces the size of the maven `pom.xml` file for that consuming module; it simply needs to reference _this_ module using the `mixin-maven-plugin`.

The appropriate configuration is included in a `<profile>` which is automatically included in all builds.
This profile can be disabled using a Maven property.




== How to Configure

To configure:

* copy and paste the following into either the `pom.xml` of the consuming module or (better still) the `pom.xml` of the top-level parent of the consuming module: +
+
[source,xml]
----
<properties>
    ...
    <mavenmixin-isisswagger.version>0.0.3</mavenmixin-isisswagger.version>

    <isis-maven-plugin.version>1.13.1</isis-maven-plugin.version>
    ...
</properties>
----
+
and: +
+
[source,xml]
----
<build>
    <pluginManagement>
        <plugins>
            ...
            <plugin>
                <groupId>org.apache.isis.tool</groupId>
                <artifactId>isis-maven-plugin</artifactId>
                <version>${isis-maven-plugin.version}</version>
            </plugin>
            ...
        </plugins>
    </pluginManagement>
</build>
----

* update the following property/ies in the `pom.xml` of the consuming `webapp` module: +
+
[source,xml]
----
<properties>
    ...
    <isis-maven-plugin.swagger.appManifest>                             <!--1-->
        domainapp.application.manifest.DomainAppAppManifest
    </isis-maven-plugin.swagger.appManifest>
    <isis-maven-plugin.swagger.dependency.groupId>                      <!--2-->
        ${project.groupId}
    </isis-maven-plugin.swagger.dependency.groupId>
    <isis-maven-plugin.swagger.dependency.artifactId>                   <!--3-->
        simpleapp-application
    </isis-maven-plugin.swagger.dependency.artifactId>                 
    <isis-maven-plugin.swagger.format>                                  <!--4-->
        JSON
    </isis-maven-plugin.swagger.format>
    ...
</properties>
----
<1> the fully qualified class name of the `AppManifest` that references the module(s) to validate.
    The default relates to that of the simpleapp example application, which will almost certainly require changing.
<2> (optional) the `groupId` of the dependency containing the `AppManifest` specified above.
    Defaults to `${project.groupId}`, which in most cases will be correct
<3> the `artifactId` of the dependency containing the `AppManifest` specified above.
    The default relates to that of the simpleapp example application, which will almost certainly require changing.
<4> (optional) the format of the generated files, either `JSON` or `YAML`.
    If not specified, then the default is `JSON`.

* add the following to the `pom.xml` of the consuming module: +
+
[source,xml]
----
<build>
    <plugins>
        <plugin>
            <groupId>com.github.odavid.maven.plugins</groupId>
            <artifactId>mixin-maven-plugin</artifactId>
            <version>0.1-alpha-39</version>
            <extensions>true</extensions>
            <configuration>
                <mixins>
                    <mixin>
                        <groupId>com.danhaywood.mavenmixin</groupId>
                        <artifactId>isisswagger</artifactId>
                        <version>${mavenmixin-isisswagger.version}</version>
                    </mixin>
                </mixins>
            </configuration>
        </plugin>
    </plugins>
</build>
----

* Specify the mandatory input properties (see above).


To disable the (profile contributed by this) mixin, pass the following system property to `mvn`:

[source,bash]
----
mvn -Dskip.mavenmixin-isisswagger
----


== How to Use


The plugin is bound to Maven's `package` phase:

[source,bash]
----
mvn package
----

This will generate Swagger definition files in the `target/generated-resources/isis-swagger` directory.
These can then be used in turn link:http://swagger.io/swagger-codegen/[generate client-side stubs] against the REST API provided by the link:http://isis.apache.org/guides/ugvro.html[Restful Objects viewer]



== Known issues

None currently



== Change Log

* `0.0.3` - updates README for properties and plugin management, shortens property names and profile id
* `0.0.2` - defines the `groupId` and `artifactId` properties to specify the dependency containing the app manifest.
   Also, the appManifest property wasn't actually being used.
* `0.0.1` - first release; released for Apache Isis 1.13.1




== Legal Stuff

=== License

[source]
----
Copyright 2016~date Dan Haywood

Licensed under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
----



=== Dependencies

This mixin module relies on the link:https://github.com/odavid/maven-plugins[com.github.odavid.maven.plugins:mixin-maven-plugin], released under Apache License v2.0.



== Maven deploy notes

The module is deployed using Sonatype's OSS support (see
http://central.sonatype.org/pages/apache-maven.html[user guide] and http://www.danhaywood.com/2013/07/11/deploying-artifacts-to-maven-central-repo/[this blog post]).

The `release.sh` script automates the release process.
It performs the following:

* performs a sanity check (`mvn clean install -o`) that everything builds ok
* bumps the `pom.xml` to a specified release version, and tag
* performs a double check (`mvn clean install -o`) that everything still builds ok
* releases the code using `mvn clean deploy`
* bumps the `pom.xml` to a specified release version

For example:

[source]
----
sh release.sh 0.0.3 \
              0.0.4-SNAPSHOT \
              dan@haywood-associates.co.uk \
              "this is not really my passphrase"
----

where

* `$1` is the release version
* `$2` is the snapshot version
* `$3` is the email of the secret key (`~/.gnupg/secring.gpg`) to use for signing
* `$4` is the corresponding passphrase for that secret key.

Other ways of specifying the key and passphrase are available, see the ``pgp-maven-plugin``'s
http://kohsuke.org/pgp-maven-plugin/secretkey.html[documentation]).

If the script completes successfully, then push changes:

[source]
----
git push origin master
git push origin 0.0.3
----

If the script fails to complete, then identify the cause, perform a `git reset --hard` to start over and fix the issue before trying again.
Note that in the `dom`'s `pom.xml` the `nexus-staging-maven-plugin` has the `autoReleaseAfterClose` setting set to `true` (to automatically stage, close and the release the repo).
You may want to set this to `false` if debugging an issue.

According to Sonatype's guide, it takes about 10 minutes to sync, but up to 2 hours to update http://search.maven.org[search].
